### PR TITLE
Re-add example CI

### PR DESCRIPTION
**Pull request by luispadron**
#75 removed CI for the example because they had gone stale and GitHub workers no longer support iOS 13 or `macos-11`. To not block other work (such as better support for SPM) I removed these tests. We should ideally continue to test the examples but requires more work.

This will require updates to support one of the macos & iOS platforms available to GitHub action workers: https://github.com/actions/runner-images/tree/main/images/macos We'll also need to update snaphot images.

### CODE REVIEW

**Comment by luispadron** [comment]
maco-11 was dropped in: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/

**Comment by dfed** [comment]
Makes sense! I know @NickEntin has been excited about upgrading the snapshot images to latest as well. Certainly not the easiest lift.

**Review by NickEntin — APPROVED** [review]

**Comment by NickEntin** [comment]
@luispadron Looks like I was removed as an admin on the repo - can you add me back or mark the `Pod Lint` and `Xcode Build` jobs as required? Also would be good to add @dfed to contributors so he can do approving code reviews. Thanks!

**Comment by luispadron** [comment]
Thanks for getting this updated! Added @dfed as maintainer

**Pull request merged**
